### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [eclipse-iofog/Controller#611]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/eclipse-iofog/Controller/blob/develop/package.json#L76

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by Pixcell** [comment]
Thank you very much @DanielRuf .

We have removed it.
